title: Semperti
description: Comunidades técnicas de semperti
author: Blogs
logo: /static/img/logo-semperti.svg
github: https://github.com/semperti
about: Comunidades técnicas

baseurl: ""
url: "http://semperti.github.io"

disqus_shortname: blog-comunidades-tecnicas
google_analytics:

share:
  twitter_username: \@_semperti
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
